name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
        working-directory: ./tools/brief/
      - run: node main.js
        working-directory: ./tools/brief/