name: Manual trigger
run-name: Build ImGui_GM for Windows
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}
        - uses: abel0b/setup-premake@v2.3
          with:
            version: "5.0.0-beta2"
        - name: Run Premake
          run: |
            premake5 gmake2
            make
